//! Generates the isolated `CODEX_HOME/config.toml` (002 TK-001, TK-002).
//!
//! The file never contains secrets: providers point at the local gateway and
//! read the loopback token from `AURA_GATEWAY_TOKEN`; MCP secrets are injected
//! as environment variables by the host.

use std::io;
use std::path::{Path, PathBuf};
use toml::{Table, Value};

pub const CHATGPT_PLAN_PROVIDER: &str = "aura-chatgpt-plan";
pub const GATEWAY_TOKEN_ENV: &str = "AURA_GATEWAY_TOKEN";
pub const MCP_TOKEN_ENV: &str = "AURA_MCP_TOKEN";

/// Other modules add sections (BYOK providers, MCP servers, feature flags).
pub trait ConfigContributor: Send + Sync {
    fn contribute(&self, config: &mut Table);
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BaseConfig {
    /// Port of the local gateway (changes every run).
    pub gateway_port: u16,
    /// Port of the Aura MCP endpoint (same loopback server).
    pub mcp_port: Option<u16>,
    pub web_search: bool,
    pub memories: bool,
    /// `unelevated` (default) or `elevated`.
    pub windows_sandbox: String,
}

impl Default for BaseConfig {
    fn default() -> Self {
        Self {
            gateway_port: 0,
            mcp_port: None,
            web_search: true,
            memories: false,
            windows_sandbox: "unelevated".into(),
        }
    }
}

fn table(entries: impl IntoIterator<Item = (&'static str, Value)>) -> Value {
    Value::Table(
        entries
            .into_iter()
            .map(|(k, v)| (k.to_string(), v))
            .collect(),
    )
}

pub fn gateway_base_url(port: u16, provider_id: &str) -> String {
    format!("http://127.0.0.1:{port}/p/{provider_id}/v1")
}

/// Builds the config document.
pub fn render(base: &BaseConfig, contributors: &[&dyn ConfigContributor]) -> Table {
    let mut root = Table::new();
    root.insert(
        "model_provider".into(),
        Value::String(CHATGPT_PLAN_PROVIDER.into()),
    );
    root.insert(
        "web_search".into(),
        Value::String(if base.web_search { "live" } else { "disabled" }.into()),
    );

    let mut providers = Table::new();
    providers.insert(
        CHATGPT_PLAN_PROVIDER.into(),
        table([
            ("name", Value::String("ChatGPT plan".into())),
            (
                "base_url",
                Value::String(gateway_base_url(base.gateway_port, "chatgpt-plan")),
            ),
            ("env_key", Value::String(GATEWAY_TOKEN_ENV.into())),
            ("wire_api", Value::String("responses".into())),
            ("requires_openai_auth", Value::Boolean(false)),
            ("supports_websockets", Value::Boolean(false)),
            ("request_max_retries", Value::Integer(2)),
            ("stream_idle_timeout_ms", Value::Integer(120_000)),
        ]),
    );
    root.insert("model_providers".into(), Value::Table(providers));

    root.insert(
        "windows".into(),
        table([("sandbox", Value::String(base.windows_sandbox.clone()))]),
    );
    root.insert(
        "features".into(),
        table([("memories", Value::Boolean(base.memories))]),
    );

    if let Some(port) = base.mcp_port {
        let mut servers = Table::new();
        servers.insert(
            "aura".into(),
            table([
                ("url", Value::String(format!("http://127.0.0.1:{port}/mcp"))),
                ("bearer_token_env_var", Value::String(MCP_TOKEN_ENV.into())),
                ("default_tools_approval_mode", Value::String("auto".into())),
                ("required", Value::Boolean(false)),
            ]),
        );
        root.insert("mcp_servers".into(), Value::Table(servers));
    }

    for c in contributors {
        c.contribute(&mut root);
    }
    root
}

/// Helper for contributors: returns (creating) a nested table.
pub fn section<'a>(root: &'a mut Table, key: &str) -> &'a mut Table {
    let entry = root
        .entry(key.to_string())
        .or_insert_with(|| Value::Table(Table::new()));
    if !entry.is_table() {
        *entry = Value::Table(Table::new());
    }
    entry.as_table_mut().expect("table")
}

/// Writes `config.toml` atomically and returns the home directory.
pub fn prepare(
    home: &Path,
    base: &BaseConfig,
    contributors: &[&dyn ConfigContributor],
) -> io::Result<PathBuf> {
    std::fs::create_dir_all(home)?;
    let doc = render(base, contributors);
    let text = format!(
        "# Generated by Aura on every app-server start. Do not edit: changes are overwritten.\n{}",
        toml::to_string(&doc).map_err(io::Error::other)?
    );
    let tmp = home.join("config.toml.tmp");
    std::fs::write(&tmp, text)?;
    std::fs::rename(&tmp, home.join("config.toml"))?;
    Ok(home.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Byok;
    impl ConfigContributor for Byok {
        fn contribute(&self, config: &mut Table) {
            let providers = section(config, "model_providers");
            providers.insert(
                "aura-groq".into(),
                table([
                    ("name", Value::String("Groq".into())),
                    ("base_url", Value::String(gateway_base_url(4100, "groq"))),
                    ("wire_api", Value::String("responses".into())),
                ]),
            );
        }
    }

    #[test]
    fn config_has_plan_provider_without_secrets_and_contributions() {
        let base = BaseConfig {
            gateway_port: 4100,
            mcp_port: Some(4100),
            ..Default::default()
        };
        let doc = render(&base, &[&Byok]);
        let text = toml::to_string(&doc).unwrap();
        assert!(text.contains("model_provider = \"aura-chatgpt-plan\""));
        assert!(text.contains("base_url = \"http://127.0.0.1:4100/p/chatgpt-plan/v1\""));
        assert!(text.contains("env_key = \"AURA_GATEWAY_TOKEN\""));
        assert!(text.contains("supports_websockets = false"));
        assert!(text.contains("[model_providers.aura-groq]"));
        assert!(text.contains("url = \"http://127.0.0.1:4100/mcp\""));
        assert!(!text.to_lowercase().contains("sk-"));
    }

    #[test]
    fn prepare_writes_file_atomically() {
        let dir = tempfile::tempdir().unwrap();
        prepare(dir.path(), &BaseConfig::default(), &[]).unwrap();
        let text = std::fs::read_to_string(dir.path().join("config.toml")).unwrap();
        assert!(text.starts_with("# Generated by Aura"));
        assert!(!dir.path().join("config.toml.tmp").exists());
    }
}
